---
title: "EDA_Markdown_NK"
author: "Noah Kreski"
date: "November 19, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```

```{r eda linkage}
HIV_data = read_csv("./data/DOHMH_HIV_AIDS_Annual_report.csv")
Linkage_data_male = HIV_data%>%
               janitor::clean_names()%>%
               filter(borough %in% c("All"))%>%
               filter(!(age %in% c("All")))%>%
               filter(gender == "Male")
Linkage_data_male%>%
               ggplot(aes(x = year, y = percent_linked_to_care_within_3_months, group = age, color = age))+geom_point() + geom_line()
Linkage_data_female = HIV_data%>%
               janitor::clean_names()%>%
               filter(borough %in% c("All"))%>%
               filter(!(age %in% c("All")))%>%
               filter(gender == "Female")
Linkage_data_female%>%
               ggplot(aes(x = year, y = percent_linked_to_care_within_3_months, group = age, color = age))+geom_point() + geom_line()         
```

```{r eda aids diagnosis rate}
HIV_data = read_csv("./data/DOHMH_HIV_AIDS_Annual_report.csv")
AIDS_diagnosis_data = HIV_data%>%
               janitor::clean_names()%>%
               filter(borough %in% c("All"))%>%
               filter((age %in% c("All")))%>%
               filter(!(gender %in% c("Transgender")))%>%
               filter(race %in% c("All"))
AIDS_diagnosis_data%>%
               ggplot(aes(x = year, y = aids_diagnosis_rate, group = gender, color = gender))+geom_point() + geom_line()
              
```

```{r eda HIV diagnosis rate by borough}
HIV_data = read_csv("./data/DOHMH_HIV_AIDS_Annual_report.csv")
HIV_diagnosis_data = HIV_data%>%
               janitor::clean_names()%>%
               filter(uhf %in% c("All"))%>%
               filter(borough != "All")%>%
               filter(gender == "All")%>%
               filter(age == "All")
HIV_diagnosis_data%>%
            ggplot( aes(fill=reorder(borough, -hiv_diagnosis_rate), y=hiv_diagnosis_rate, x=year)) +
    geom_bar(position="dodge", stat="identity") + labs(title = "HIV Diagnosis Rate by Borough over Time", y = "HIV Diagnosis Rate", x = "Year", fill = "Borough") 
              
```