---
title: "Final_Report"

author: "Noah Kreski(Ntk2109), Briana Lettsome(Bjl2150), Sunny Siddique (as5457), 
Bryce Wong (baw2160), David Yu (ky2288)"
date: "December 6th, 2018"
output: github_document
---

##**Introduction**




## **Methods**

Data: Source, scraping method, cleaning, etc.

  The data that was utilized for this project was the New York City Department of
Health and Mntal Hygeine HIV/AIDS Surveillance Annual Report. The dataset was 
downloaded from NYCOpen Data, an open website that provides information and data to 
New Yorkers by the NYC government, an imported into R as a csv file. 
  Within this particular datThe data contained within the dataset were collected between the years 2011 through 2016. The HIV/AIDS surveillance Annual Report contains eighteen variables, including
year, age, race, HIV diagnoses, deaths, and percent viral suppression. The variables used within the visualizations are a followed:





Exploratory analysis: Visualizations, summaries, and exploratory statistical analyses. Justify the steps you took, and show any major changes to your ideas.


##**Results**




##**Discussion**


